version 2:

jobs:
  build:
    docker:
      -image: circleci/openjdk:11-jdk
    working_directory: ~/fake-user-app
    steps:
      - checkout
      - run:
            name: Create a Directory
            command: mkdir -p ~/fake-user-app

      - restore_cache:
        - keys:
            - fake-user-app-dependencies-{{ checksum "pom.xml" }}

      - run:
           name: Build (Create JAR File)
           command: mvn clean package -DskipTest
      - save_cache:
          paths:
            - ~/.m2
          key: fake-user-app-dependencies-{{ checksum "pom.xml" }}
      - persist_to_workspace:
          root: ~/fake-user-app
          paths:
            - .

  test:
    machine: true
    working_directory: ~/fake-user-app

    steps:
      - attach_workspace:
          at: ~/fake-user-app

      - run:
          name: Start PostgreSQL Test Container
          command: |
            docker run -d \
              --name test-db \
              -p 5442:5432 \
              -e POSTGRES_DB=fake_user_app \
              -e POSTGRES_USER=postgres \
              -e POSTGRES_PASSWORD=cydeo123. \
              postgres:latest

      - run:
          name: Run Integration Tests and Unit Tests
          command: |
            mvn test \
              -Dskip.unit.tests=false \
              -Dskip.integration.tests=false \
              -Dspring.datasource.url="jdbc:postgresql://localhost:5442/fake_user_app" \
              -Dspring.datasource.username="postgres" \
              -Dspring.datasource.password="cydeo123."

  docker-image-create-and-push:
    machine: true
    working_directory: ~/fake-user-app

    steps:
      - attach_workspace:
          at: ~/fake-user-app
      - run:
          name: create docker image
          command: docker build -t 020651500043.dkr.ecr.us-east-2.amazonaws.com/fake-user-app:latest .
      - run:
          name: Login to Image Repo (AWS ECR)
          command: aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 020651500043.dkr.ecr.us-east-2.amazonaws.com
      - run:
          name: Push the image to ECR
          command: docker push 020651500043.dkr.ecr.us-east-2.amazonaws.com/fake-user-app:latest
  deploy:
    machine: true

    steps:
      -run:
        name: Connect to EC2 Server and run the image
        command: | 
          ssh -o "StrictHostKeyChecking=no" ubuntu@ec2-18-134-160-90.eu-west-2.compute.amazonaws.com <<'ENDSSH'
          /bin/bash ~/fake-user-app/deploy_image.sh
          
          ENDSSH 


workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            -build
      - docker-image-create-and-push:
          requires:
            -test
      - deploy:
          requires:
            -docker-imagee-create-and-push